### ISSUE TITLE
Don't Touch Master or Testing without Ask.

### ISSUE THREAD

**Issue by liberodark** [YunoHost-Apps/jellyfin_ynh#41]
@ericgaspar @tituspijean merci de passer par des PR et en ayant tout testé.

**Comment by tituspijean** [comment]
@liberodark, regardless of being the app's maintainer:

1) The app was failing Continuous Integration and could not be installed [since *at least* June](https://ci-apps.yunohost.org/ci/apps/jellyfin/).
2) Putting the app in YunoHost-Apps means that the community can step in to help and fix things, there is no need to be territorial.
3) Due process was followed. Dev branch > **PR** > Testing branch > **PR** > Master, with quite enough time to step in and review it.
4) Since the app was not installable, the "upgrade from older commit" test was overlooked by the CI ([Step 5/9](https://ci-apps.yunohost.org/ci/job/2052)). If you have a bug regarding the upgrade of the app, you are most welcome to open an issue regarding this.

**Comment by kay0u** [comment]
The application had been level 0 for a [little while](https://github.com/YunoHost/apps/commit/bc14ce92567b5288a86d242ad8806d4ef8c93b12) and did not follow the recommendations.
You are the maintainer of the application, but you don't own it, and others have the right to contribute to it.
Moreover they used the [ci-dev](https://ci-apps-dev.yunohost.org/jenkins/job/jellyfin_ynh%20(tituspijean)/24/console) before merge in testing. [This PR](https://github.com/YunoHost-Apps/jellyfin_ynh/pull/38.) was opened almost a month ago and it greatly improves the quality of the package since it takes it from level 0 to level 7.

 There is no reason to revert the work they did. If there is a problem when upgrading from the old version (which seems normal to me since it was level 0 and nobody could install it to try the upgrade), instead of reverting the work, we must open an issue with logs, in order to move forward and remain constructive. I'm sure they will be happy to help on this app that YunoHost really lacks in a decent quality.

So thank you to open a new issue, to bring logs, and please, don't do that again.

**Comment by liberodark** [comment]
Im go to revert again this work broke the APP
and you CI dont make all tests...

**Comment by liberodark** [comment]
Now app is LVL 7 and non broken

**Comment by alexAubin** [comment]
1. **You're still not explaining why/what it supposedly broke, despite the team being genuinely interested in what happened exactly.**

2. Yes, the app passing the tests on the CI is not a 100% guarantee that the app works, but here's we're talking about an app **not** passing any tests on the CI, which **usually is *a pretty good indicator that the app really is broken***. So nobody "broke" anything by merging the PR, considering the app was **already broken** since quite a while. If you have some ideas on making the CI tests more accurate and reliable, we would be glad to hear about those.

3. The initial PR proposing a rework of the app is from ~28 days ago. Contributors pinged you multiple times for a review or any thoughts on it, and you did not respond.

4. This app is in the Yunohost-Apps organization. The very purpose of this organization is, among other things, that the packaging community *can* come and contribute / maintain the application ecosystem. Especially because one may stop maintaining an app he/she was previously maintaining without a warning. 

5. And then yes, when it comes to apps that are broken according to our automatic testing, we tend to take the liberty to merge without an explicit approval, because, again, can't hurt that much considering it's already broken. (And again in that case, there was plenty of buffer time to react).

Summarizing : volunteers used their free time and energy to fix your app for free, politely asked for feedback that you did not provide, yet you suddenly show up and throw a drama because you're claiming they broke "your" app without explaining why, and aggressively revert their work. What do you think that sounds like ?

If you disagree with the fact that the community may intervene on broken apps (or other critical issues), you are free to create app repositories anywhere else - just understand that Yunohost will tend to discourage admins to install apps that are not maintain-able by the community.

>Si on doit faire de la m**** sur les projets des autres alors très bien vous pourrez me le préciser et je ferait l'app de mon coté.
>Sachant que j'ai poussé une bonne partie de vos apps.

If you really want to play with this : [let's have a look at the numbers](https://dash.yunohost.org/app_maintainer_dash/liberodark). There are 22ish apps where you are flagged as maintainer. 5 of them are actually flagged as "working" on the app list, and only 3 are levels 7 ... and pretty sure that's thanks to the same people that worked on fixing Jellyfin ! (Basically the same people that maintain the currently 160+ level 7 apps of the Yunohost catalog) So maybe you can give them a bit of credit too, 'cause apps don't magically pass level 7...

**Comment by tituspijean** [comment]
@kay0u and @alexAubin have covered the team-work-related issues. Let me get into specifics. I am trying very hard to not talk shit like you are doing.

> this work broke the APP

> Et il y a pas mal de soucis dedans un ce n'est pas un bon point.

> Have fixed issues

I have the CI, my installations in a virtual machine and on a Raspberry Pi that I used last night to prove you otherwise. Please, *please*, explain how this app after our fix was broken for you.

What issues?

> Cela casse l'application alors je ne comprends pourquoi vous voulez forcer une PR.

How was it broken? We "forced" the PR because no work was being done on it.

> Qui rend instable l'application de plus votre Ci n'est pas un gage de fonctionnement ou stabilité.

Describe "unstable".
And yes, correct, the CI is not an omnipotent indicator, but it is still a good one. And if upgrade fails, it's great we have the backup system, right?

> Now app is LVL 7 and non broken

> Normally the app is now Level 7 on your CI without breaking ARM compatibility.

How have you tested it, to say it is level 7? You have no test under your name in the dev CI. If you rely on the badge in the README, this badge was generated from our fix, not your. (check the date)

> It is good that you are participating but I am the maintainer of this application and those from the beginning.

Then do not abandon it for months. Your patch made in September did not fix it for me, and the CI agrees.

> There are concerns that are specific to this application that's why I didn't want to break everything.

What. are. the. *concerns*. Do not behave all mysterious, if there are specific steps to take to package this app, disclose them.

---

I cannot say anything but thank you for making me discover Jellyfin after the Emby drama. But here you are not behaving like a team player. We want to understand what, technically, your issue is with our fix.

**Comment by liberodark** [comment]
@alexAubin Pardon je répond en FR je suis trop fatigué :D

1. **You're still not explaining why/what it supposedly broke, despite the team being genuinely interested in what happened exactly.**
Le problème viens de pas mal de chose autre le style que j'aime pas mais c'est pas trop grave.
Le soucis est sur ARM principalement le fait qu'il sont un soucis bien spécifique avec ffmpeg qui si il est utilisé depuis leur dépot vous etes sur que votre applications ne peut lire aucun film.
N'avré il était 6h du matin j'ai zappé...

2. Yes, the app passing the tests on the CI is not a 100% guarantee that the app works, but here's we're talking about an app **not** passing any tests on the CI, which **usually is *a pretty good indicator that the app really is broken***. So nobody "broke" anything by merging the PR, considering the app was **already broken** since quite a while. If you have some ideas on making the CI tests more accurate and reliable, we would be glad to hear about those.

Considéré comment cassé ne veux pas dire quel ne fonctione pas encore une fois votre CI n'est en aucun cas un gage de fonctionnement. Après cela ce discute.
Disons aussi que j'aime pas trop l'approche de passé par des Call pythons. Mais c'est une autre histoire.

3. The initial PR proposing a rework of the app is from ~28 days ago. Contributors pinged you multiple times for a review or any thoughts on it, and you did not respond.

Oui effectivement j'ai pas vu son travail depuis 28 jours c'est exacte.
Je ne connaissez pas cette PR avec le confinement j'ai eu pas mal de soucis.
De plus je participe sur pas mal d'autres projets. Et je n'ai pas vu ce point précise.
J'en suis désolé.

4. This app is in the Yunohost-Apps organization. The very purpose of this organization is, among other things, that the packaging community *can* come and contribute / maintain the application ecosystem. Especially because one may stop maintaining an app he/she was previously maintaining without a warning. 

Bien sur cela je le comprend parfaitement.

5. And then yes, when it comes to apps that are broken according to our automatic testing, we tend to take the liberty to merge without an explicit approval, because, again, can't hurt that much considering it's already broken. (And again in that case, there was plenty of buffer time to react).

Je peux le comprendre mais avant d'etre un maintenaneur je suis aussi un utilisateur de cette apps.
Ayant pas réussi à comminiqué sur element j'ai eu personne.
Cela ma déranger sur le coup mais j'ai quand meme commencer à regarder ça PR car je respecte tout travail.

Summarizing : volunteers used their free time and energy to fix your app for free, politely asked for feedback that you did not provide, yet you suddenly show up and throw a drama because you're claiming they broke "your" app without explaining why, and aggressively revert their work. What do you think that sounds like ?

Ce n'est pas la PR le problème en aucun cas. Encore cela enerve mais ça va.
Comme vous l'avez vu au début j'ai rien dit de spécialement seulement : 

`@ericgaspar @tituspijean merci de passer par des PR et en ayant tout testé.`

Car bon c'est aussi moi qui est pas vu cette PR.
Non la ou j'ai était énervé c'est avec @kay0u car j'ai pas meme pas eu le temps de finir le taff pour le remettre dans le master sans casser l'app.

If you disagree with the fact that the community may intervene on broken apps (or other critical issues), you are free to create app repositories anywhere else - just understand that Yunohost will tend to discourage admins to install apps that are not maintain-able by the community.

Cela il y a pas de problème et vous le savez je suis très cool et ne dérange pas pour rien.

>Si on doit faire de la m**** sur les projets des autres alors très bien vous pourrez me le préciser et je ferait l'app de mon coté.
>Sachant que j'ai poussé une bonne partie de vos apps.

If you really want to play with this : [let's have a look at the numbers](https://dash.yunohost.org/app_maintainer_dash/liberodark). There are 22ish apps where you are flagged as maintainer. 5 of them are actually flagged as "working" on the app list, and only 3 are levels 7 ... and pretty sure that's thanks to the same people that worked on fixing Jellyfin ! (Basically the same people that maintain the currently 160+ level 7 apps of the Yunohost catalog) So maybe you can give them a bit of credit too, 'cause apps don't magically pass level 7...

Non j'en suis consience ce n'est pas le soucis certaines apps sont aussi assez complexe.
Et encore une fois cette PR est une bonne chose. Je suis content que l'app passe au niveau 7.
Mais avec quelques correction et c'est fait.

La méprise ce n'est pas la PR en elle meme qui me pose soucis.
Mais cela fait uniquement suite au comportement de @kay0u 
J'ai réellement passé toute la journée à tenter de joindre quelqu'un sur element pour en discuter.
J'ai aussi sauvegardé le travail fait et iméditement comment à réintégré ligne par ligne le travail de cette PR car il est majoriairement bon. Donc cela est aussi bon pour les utilisateurs.

**Comment by liberodark** [comment]
@tituspijean sache le j'ai jamais écrit que tu avait fait de la merde mais j'ai pas un bon anglais.
Donc j'ai dit : Your work is not good @tituspijean this master make app broken...
Sous le coup de l'enervement.
Rassure toi ta PR est très bien majoritairement comme je l'ai dit je ne suis pas fan du style mais c'est très prore :D 
Le seul point sur le quel je parler en disans de faire de la merde c'est pour @kay0u après il est pas au courant que j'ai tenter de vous contacter pour en discuter sachez bien que c'est seulement seulement sous le coup de l'enervement.
Mais je m'en excuse @kay0u @alexAubin @tituspijean @ericgaspar 
J'ai rien contre votre PR seulement le forcing qu'il y a eu.
N'avré que l'ont est pas pu en discuter calmement comme je le voulais en début.

**Comment by liberodark** [comment]
Pour pouvoir en discuter calmement serait il possible d'avoir le lien matrix yunohost packager ? Ce sera mieux que ici ou si vous voulez me mp mon pseudo c'est liberodark.

**Comment by kay0u** [comment]
> Issue: Don't Touch Master or Testing without Ask.

> Commit: Revert "Testing (#39)"

I'm sorry, but you can't do that. Especially without providing any reason, any logs, and just saying "this work broke the APP
and you CI dont make all tests". Before this PR the app was uninstallable.

The right way to deal with a problem is : 
- Create an issue, explain your problem.
- Create a new PR, explain how/why the problem is solved.

The CI may not be perfect, but when it say "ynh_add_nginx_config is now an official helper since version '2.7.2'", there is probably a reason. When the install fails with 
```
Warning: yunohost.hook <lambda> - [1482.1] E: Packages need to be removed but remove is disabled.
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libass5' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libbluray1' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libva-drm1' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libva-x11-1' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libva1' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libx264-148' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libx265-95' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] E: Package 'libwebpmux2' has no installation candidate
Warning: yunohost.hook <lambda> - [1482.1] Unable to install dependencies
```
It's probably not a false positive error.

> Pour pouvoir en discuter calmement serait il possible d'avoir le lien matrix yunohost packager ? Ce sera mieux que ici ou si vous voulez me mp mon pseudo c'est liberodark

https://yunohost.org/#/chat_rooms

You can use https://kiwiirc.com/nextclient/irc.freenode.net/yunohost-apps if you want

**Comment by liberodark** [comment]
Thank you for the feedback kayou it will be corrected as soon as possible.
So as not to impact the quality of the application. @kay0u

**Comment by alexAubin** [comment]
So now that things cooled down a bit. 

We discussed this during today's meeting and collectively decided to communicate the following : 

1. We confirmed that the way the "rework" PR was handled was legitimate, considering that a) it followed the usual recommended development workflow, b) the app was broken and the proposed work fixed the app, as demonstrated by multiple tests on the CI, c) the contributors pinged you for feedback which you did not provide, and d) this app is hosted in the Yunohost-Apps organization, which purpose is precisely to allow the community to contribute/maintain broken or unmaintained apps.

2. The fact that you may personally not trust the official CIs doesn't really matter (you did not provide any concrete facts to support that kind of claims, and even less proposals for improvements). You've been provided with clear logs / error messages that shows why the app is not working. Conversely, the fact that the app worked "on your machine" is by no mean an objective criteria for claiming that the app was "working" before the proposed work got merged.

3. Your reaction to the whole situation was not appropriate because : 
   - you aggressively reverted **multiple times** the legitimate work of volunteers without any proper discussion
   - **even if** the work broke a functional app (which it didn't, since we're talking about the opposite), reacting aggressively is not okay, and instead you should simply discuss calmly what happened with the other members of the community
   - you claimed multiple times that volunteers broke "your" app without providing any details to support that claim
   - you tried to justify your behavior by pointing at other people

4. At the time we were discussing this in the meeting (and this is still the case) the app is **still not working** because of the revert war, whereas the internal CI shows that the proposed work was fixing the app. Namely these tests : 
   - The proposed work that got reverted (level 7) : https://ci-apps-dev.yunohost.org/jenkins/job/jellyfin_ynh%20(tituspijean)/lastBuild/console
   - The current branch (level 0 with an obvious dependency issue) : https://ci-apps-dev.yunohost.org/jenkins/job/jellyfin_ynh%20liberodark%20(tituspijean)/lastBuild/console

Also you claimed that the app was broken on ARM board, then Kayou took the time to test the install on a RPi and found no issue, and you did not provide any additional explanations or concrete details on why/what it is that's not working exactly.

5. **We therefore decided the following** : 
   - since you seem absolutely confident about fixing the app "your way", very well : you're free to [fix the app](https://i.imgflip.com/4mtgkt.jpg) **in a timely manner**.
   - **if following a delay of our choosing, the app is still not demonstrated to be level 7, then yes, we *will* "Touch Master or Testing without Ask"**, a.k.a apply whichever changes which are deemed necessary on the repo to make the app level 7 (considering that the work for this has already been done, and this whole story just feels like an epic waste of time anyway)
   - **if you persist in reverting legit work that is aimed at fixing this app, your write access to this repository and other repositories may be suspended**
   - **if you again react inappropriately to similar situations in the future (here or elsewhere), your write access to this repository and other repositories may be suspended**

6. We want you to take good note of the fact that people from the community may contribute to other apps for which you are currently flagged as maintainer. The corresponding pull requests authors will usually make sure that there's enough buffer time (typically a week or two at least) before deciding to merge if no feedback is provided. That amount of time may however be way shorter if the app is broken entirely, broken in specific situations, suffers from significant security issues, or suffers from any issue that the community collectively judges to be important enough to justify a quick-merge procedure. We can also only encourage you to take a better look at the variety of tools and processes related to quality and testing (in particular the CI) to make sure that "your" apps are functional and level 5+, which is a necessary condition for your app to be effectively usable by regular users. If you believe there are improvements to be made to the testing tools, then you are free to propose them. But for the love of god, when claimining that something doesn't work, please provide the damn logs.

**Comment by alexAubin** [comment]
c.f. https://github.com/YunoHost-Apps/jellyfin_ynh/issues/46

Tests still failing 5 days later, no feedback.

Master and testing branches were reverted to their state before the shitstorm.
